
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package compiladorcorregir;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int BARRA = 4;
  public static final int ALFABETO = 5;
  public static final int CORREGIR = 3;
  public static final int IMPRIMIR = 2;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IMPRIMIR",
  "CORREGIR",
  "BARRA",
  "ALFABETO"
  };
}

